In [28]:
# importing libraries

import pandas as pd
import numpy as np
# for pre-processing
from sklearn import preprocessing
from sklearn.model_selection import KFold,cross_val_score

from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [29]:
df=pd.read_csv('/content/train.csv')

<ipython-input-29-a43e47edc79e>:1: DtypeWarning: Columns (26) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv('/content/train.csv')

In [30]:
df.head()

,ID,Customer_ID,Month,Name,Age,SSN,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,...,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
0,0x1602,CUS_0xd40,January,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,1824.843333,3,...,_,809.98,26.822620,22 Years and 1 Months,No,49.574949,80.41529543900253,High_spent_Small_value_payments,312.49408867943663,Good
1,0x1603,CUS_0xd40,February,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,NaN,3,...,Good,809.98,31.944960,NaN,No,49.574949,118.28022162236736,Low_spent_Large_value_payments,284.62916249607184,Good
2,0x1604,CUS_0xd40,March,Aaron Maashoh,-500,821-00-0265,Scientist,19114.12,NaN,3,...,Good,809.98,28.609352,22 Years and 3 Months,No,49.574949,81.699521264648,Low_spent_Medium_value_payments,331.2098628537912,Good
3,0x1605,CUS_0xd40,April,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,NaN,3,...,Good,809.98,31.377862,22 Years and 4 Months,No,49.574949,199.4580743910713,Low_spent_Small_value_payments,223.45130972736786,Good
4,0x1606,CUS_0xd40,May,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,1824.843333,3,...,Good,809.98,24.797347,22 Years and 5 Months,No,49.574949,41.420153086217326,High_spent_Medium_value_payments,341.48923103222177,Good

In [31]:
df.isnull().sum()

ID                              0
Customer_ID                     0
Month                           0
Name                         9985
Age                             0
SSN                             0
Occupation                      0
Annual_Income                   0
Monthly_Inhand_Salary       15002
Num_Bank_Accounts               0
Num_Credit_Card                 0
Interest_Rate                   0
Num_of_Loan                     0
Type_of_Loan                11408
Delay_from_due_date             0
Num_of_Delayed_Payment       7002
Changed_Credit_Limit            0
Num_Credit_Inquiries         1965
Credit_Mix                      0
Outstanding_Debt                0
Credit_Utilization_Ratio        0
Credit_History_Age           9030
Payment_of_Min_Amount           0
Total_EMI_per_month             0
Amount_invested_monthly      4479
Payment_Behaviour               0
Monthly_Balance              1200
Credit_Score                    0
dtype: int64

In [32]:
df.describe()

,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Delay_from_due_date,Num_Credit_Inquiries,Credit_Utilization_Ratio,Total_EMI_per_month
count,84998.000000,100000.000000,100000.00000,100000.000000,100000.000000,98035.000000,100000.000000,100000.000000
mean,4194.170850,17.091280,22.47443,72.466040,21.068780,27.754251,32.285173,1403.118217
std,3183.686167,117.404834,129.05741,466.422621,14.860104,193.177339,5.116875,8306.041270
min,303.645417,-1.000000,0.00000,1.000000,-5.000000,0.000000,20.000000,0.000000
25%,1625.568229,3.000000,4.00000,8.000000,10.000000,3.000000,28.052567,30.306660
50%,3093.745000,6.000000,5.00000,13.000000,18.000000,6.000000,32.305784,69.249473
75%,5957.448333,7.000000,7.00000,20.000000,28.000000,9.000000,36.496663,161.224249
max,15204.633333,1798.000000,1499.00000,5797.000000,67.000000,2597.000000,50.000000,82331.000000

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 28 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   ID                        100000 non-null  object
 1   Customer_ID               100000 non-null  object
 2   Month                     100000 non-null  object
 3   Name                      90015 non-null   object
 4   Age                       100000 non-null  object
 5   SSN                       100000 non-null  object
 6   Occupation                100000 non-null  object
 7   Annual_Income             100000 non-null  object
 8   Monthly_Inhand_Salary     84998 non-null   float64
 9   Num_Bank_Accounts         100000 non-null  int64
 10  Num_Credit_Card           100000 non-null  int64
 11  Interest_Rate             100000 non-null  int64
 12  Num_of_Loan               100000 non-null  object
 13  Type_of_Loan              88592 non-null   object
 14  Delay_from_due_date       100000 non-null  int64
 15  Num_of_Delayed_Payment    92998 non-null   object
 16  Changed_Credit_Limit      100000 non-null  object
 17  Num_Credit_Inquiries      98035 non-null   float64
 18  Credit_Mix                100000 non-null  object
 19  Outstanding_Debt          100000 non-null  object
 20  Credit_Utilization_Ratio  100000 non-null  float64
 21  Credit_History_Age        90970 non-null   object
 22  Payment_of_Min_Amount     100000 non-null  object
 23  Total_EMI_per_month       100000 non-null  float64
 24  Amount_invested_monthly   95521 non-null   object
 25  Payment_Behaviour         100000 non-null  object
 26  Monthly_Balance           98800 non-null   object
 27  Credit_Score              100000 non-null  object
dtypes: float64(4), int64(4), object(20)
memory usage: 21.4+ MB

In [34]:
df = df.dropna()

In [35]:
df.isnull().sum()

ID                          0
Customer_ID                 0
Month                       0
Name                        0
Age                         0
SSN                         0
Occupation                  0
Annual_Income               0
Monthly_Inhand_Salary       0
Num_Bank_Accounts           0
Num_Credit_Card             0
Interest_Rate               0
Num_of_Loan                 0
Type_of_Loan                0
Delay_from_due_date         0
Num_of_Delayed_Payment      0
Changed_Credit_Limit        0
Num_Credit_Inquiries        0
Credit_Mix                  0
Outstanding_Debt            0
Credit_Utilization_Ratio    0
Credit_History_Age          0
Payment_of_Min_Amount       0
Total_EMI_per_month         0
Amount_invested_monthly     0
Payment_Behaviour           0
Monthly_Balance             0
Credit_Score                0
dtype: int64

In [36]:
df = df.drop(['ID', 'SSN', 'Name', 'Customer_ID', 'Type_of_Loan', 'Occupation', 'Month', 'Monthly_Balance', 'Amount_invested_monthly'],axis = 1)

In [37]:
df.head()

,Age,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Delay_from_due_date,Num_of_Delayed_Payment,Changed_Credit_Limit,Num_Credit_Inquiries,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Payment_Behaviour,Credit_Score
0,23,19114.12,1824.843333,3,4,3,4,3,7,11.27,4.0,_,809.98,26.822620,22 Years and 1 Months,No,49.574949,High_spent_Small_value_payments,Good
6,23,19114.12,1824.843333,3,4,3,4,3,8_,11.27,4.0,Good,809.98,22.537593,22 Years and 7 Months,No,49.574949,Low_spent_Small_value_payments,Good
8,28_,34847.84,3037.986667,2,4,6,1,3,4,5.42,2.0,Good,605.03,24.464031,26 Years and 7 Months,No,18.816215,Low_spent_Small_value_payments,Standard
9,28,34847.84,3037.986667,2,4,6,1,7,1,7.42,2.0,Good,605.03,38.550848,26 Years and 8 Months,No,18.816215,High_spent_Large_value_payments,Good
10,28,34847.84_,3037.986667,2,1385,6,1,3,-1,5.42,2.0,_,605.03,33.224951,26 Years and 9 Months,No,18.816215,High_spent_Large_value_payments,Standard

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 53049 entries, 0 to 99999
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       53049 non-null  object
 1   Annual_Income             53049 non-null  object
 2   Monthly_Inhand_Salary     53049 non-null  float64
 3   Num_Bank_Accounts         53049 non-null  int64
 4   Num_Credit_Card           53049 non-null  int64
 5   Interest_Rate             53049 non-null  int64
 6   Num_of_Loan               53049 non-null  object
 7   Delay_from_due_date       53049 non-null  int64
 8   Num_of_Delayed_Payment    53049 non-null  object
 9   Changed_Credit_Limit      53049 non-null  object
 10  Num_Credit_Inquiries      53049 non-null  float64
 11  Credit_Mix                53049 non-null  object
 12  Outstanding_Debt          53049 non-null  object
 13  Credit_Utilization_Ratio  53049 non-null  float64
 14  Credit_History_Age        53049 non-null  object
 15  Payment_of_Min_Amount     53049 non-null  object
 16  Total_EMI_per_month       53049 non-null  float64
 17  Payment_Behaviour         53049 non-null  object
 18  Credit_Score              53049 non-null  object
dtypes: float64(4), int64(4), object(11)
memory usage: 8.1+ MB

In [39]:
# use label encoder to convert required columns into numbers

label_encoder = preprocessing.LabelEncoder()
df['Age'] = label_encoder.fit_transform(df['Age'])
df['Annual_Income'] = label_encoder.fit_transform(df['Annual_Income'])
df['Monthly_Inhand_Salary'] = label_encoder.fit_transform(df['Monthly_Inhand_Salary'])
df['Num_of_Loan'] = label_encoder.fit_transform(df['Num_of_Loan'])
df['Num_of_Delayed_Payment'] = label_encoder.fit_transform(df['Num_of_Delayed_Payment'])
df['Changed_Credit_Limit'] = label_encoder.fit_transform(df['Changed_Credit_Limit'])
df['Credit_Mix'] = label_encoder.fit_transform(df['Credit_Mix'])
df['Outstanding_Debt'] = label_encoder.fit_transform(df['Outstanding_Debt'])
df['Credit_History_Age'] = label_encoder.fit_transform(df['Credit_History_Age'])
df['Payment_of_Min_Amount'] = label_encoder.fit_transform(df['Payment_of_Min_Amount'])
df['Payment_Behaviour'] = label_encoder.fit_transform(df['Payment_Behaviour'])
####df['Monthly_Balance'] = label_encoder.fit_transform(df['Monthly_Balance'])
####df['Amount_invested_monthly'] = label_encoder.fit_transform(df['Amount_invested_monthly'])
df['Credit_Score'] = label_encoder.fit_transform(df['Credit_Score'])

In [40]:
df.head()

,Age,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Delay_from_due_date,Num_of_Delayed_Payment,Changed_Credit_Limit,Num_Credit_Inquiries,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Payment_Behaviour,Credit_Score
0,184,4604,3685,3,4,3,134,3,429,951,4.0,3,10500,26.822620,180,1,49.574949,3,0
6,184,4604,3685,3,4,3,134,3,460,951,4.0,1,10500,22.537593,188,1,49.574949,6,0
8,269,7905,5847,2,4,6,1,3,364,3386,2.0,1,9473,24.464031,236,1,18.816215,6,2
9,257,7905,5847,2,4,6,1,7,8,3669,2.0,1,9473,38.550848,237,1,18.816215,1,0
10,257,7906,5847,2,1385,6,1,3,0,3386,2.0,3,9473,33.224951,238,1,18.816215,1,2

In [41]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [42]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3)

In [43]:
print(x.shape)

(53049, 18)

In [44]:
print(y_train.shape)

(37134,)

In [45]:
sel = SelectFromModel(RandomForestClassifier(n_estimators = 100,max_features = 3))
sel.fit(x_train,y_train)

SelectFromModel(estimator=RandomForestClassifier(max_features=3))

In [46]:
sel.get_support()

array([False, False, False, False, False,  True, False,  True, False,
        True,  True, False,  True,  True,  True, False, False, False])

In [47]:
selected_feat= x_train.columns[(sel.get_support())]
len(selected_feat)

7

In [48]:
print(selected_feat)

Index(['Interest_Rate', 'Delay_from_due_date', 'Changed_Credit_Limit',
       'Num_Credit_Inquiries', 'Outstanding_Debt', 'Credit_Utilization_Ratio',
       'Credit_History_Age'],
      dtype='object')

In [54]:
# Creating a Random Forest Classifier model
random_forest_model = RandomForestClassifier(random_state=10)

# Fiting the model to the training data
random_forest_model.fit(x_train, y_train)

# Making predictions on the test data
pred= random_forest_model.predict(x_test)

In [50]:
np.mean(y_test==pred)

0.7710964498900409

In [51]:
# Calculating accuracy of testing data
accuracy = accuracy_score(y_test, pred)
print("Random Forest Accuracy:", accuracy)

Random Forest Accuracy: 0.7710964498900409

In [52]:
# Making predictions on the training data
pred1= random_forest_model.predict(x_train)

In [53]:
# Calculating accuracy of training data
accuracy = accuracy_score(y_train, pred1)
print("Random Forest Accuracy:", accuracy)

Random Forest Accuracy: 0.9999730705014273